# Generated by Django 6.0.5 on 2026-06-07 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
