# Generated by Django 6.0.5 on 2026-06-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(related_name='tags', to='category.category')),
                ('product', models.ManyToManyField(related_name='tags', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
